version: "3"
services:
  order-limit-service:
    image: order-limit-service
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: order-limit-service
    restart: always
    ports:
      - 5631:5631
    command: yarn start
